//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoderBunny_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePlayers
    {
        public int GamePlayerId { get; set; }
        public int GameId { get; set; }
        public int PlayerId { get; set; }
        public Nullable<int> PlayerOrder { get; set; }
        public Nullable<int> CurrentPosition { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Direction { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
