//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoderBunny_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameMove
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameMove()
        {
            this.PlayerCardUsage = new HashSet<PlayerCardUsage>();
        }
    
        public int MoveId { get; set; }
        public int GameId { get; set; }
        public int PlayerId { get; set; }
        public int DiceValue { get; set; }
        public int SequenceId { get; set; }
        public Nullable<System.DateTime> MoveTime { get; set; }
        public Nullable<int> FromX { get; set; }
        public Nullable<int> FromY { get; set; }
        public Nullable<int> ToX { get; set; }
        public Nullable<int> ToY { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerCardUsage> PlayerCardUsage { get; set; }
    }
}
