//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoderBunny_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class coderbunnyEntities : DbContext
    {
        public coderbunnyEntities()
            : base("name=coderbunnyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoardConfig> BoardConfig { get; set; }
        public virtual DbSet<CardMaster> CardMaster { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<GameMove> GameMove { get; set; }
        public virtual DbSet<GamePlayers> GamePlayers { get; set; }
        public virtual DbSet<GameTurn> GameTurn { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<PlayerCard> PlayerCard { get; set; }
        public virtual DbSet<PlayerCardUsage> PlayerCardUsage { get; set; }
        public virtual DbSet<Result> Result { get; set; }
    }
}
