//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoderBunny_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerCard
    {
        public int PlayerCardId { get; set; }
        public int PlayerId { get; set; }
        public int CardId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> GameId { get; set; }
    
        public virtual CardMaster CardMaster { get; set; }
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
